Improve name lookups
dirien/minecraft-prometheus-exporter pull request #8
Opened 2021-07-13 14:04 UTC by RuscalWorld

To learn the name of the player, exporter just creates a request to Mojang API. There are at least 2 disadvantages of this solution:
1. What if I have a server with 1000 registered players? Yes, it just makes 1000 requests to Mojang API. Just 1000 HTTP requests.
2. Cracked servers are not supported. So, some countries like Russia, where cracked servers are popular, are not supported too.

I've implemented a `--mc.name-source` flag that allows to change behavior when looking up for player name. Supported values are `mojang` and `bukkit`. 
* If set to `mojang`, it will make request to Mojang API for each player. 
* If set to `bukkit`, name will be fetched from `lastKnownName` NBT tag that added by Bukkit. 
* If `offline` or any other value is set, it will use UUID as name.

2021-07-13 14:10 UTC, RuscalWorld commented
This does not solve problem with large servers completely, but heavily optimize exporter. Loading `/metrics` endpoint still take too much time in my case. I think that some flag should be added that allows to replace separate metrics for each player with total metrics for all players.

2021-07-13 14:15 UTC, dirien commented
@RuscalWorld : Thanks for the PR. How about reducing the amount of stats to really important ones? 

Or aggregating them into a single one? Like Blocks_mined not all the different block types. Does it really matter how much obsidian i mined?

Would this reduce the time?

2021-07-13 14:29 UTC, RuscalWorld commented
> @RuscalWorld : Thanks for the PR. How about reducing the amount of stats to really important ones?
> 
> Or aggregating them into a single one? Like Blocks_mined not all the different block types. Does it really matter how much obsidian i mined?
> 
> Would this reduce the time?

I think that this will heavily reduce the response time, but all metrics can be important for different users. Maybe you don't care about how much obsidian you mined, but what if I need this metric exactly for some certain block? It would be great if there was an ability to disable certain metrics, but completely removing some of them is not a good idea.

2021-07-13 14:34 UTC, dirien commented
> I think that this will heavily reduce the response time, but all metrics can be important for different users. Maybe you don't care about how much obsidian you mined, but what if I need this metric exactly for some certain block? It would be great if there was an ability to disable certain metrics, but completely removing some of them is not a good idea.

Sounds good too, do you have any suggestions on how group the different metrices? 

So  for general statistics, we have minecraft:custom. 

For item statistics, their types are minecraft:mined, minecraft:broken, minecraft:crafted, minecraft:used, minecraft:picked_up, and minecraft:dropped. 

For mob statistics, their types are minecraft:killed and minecraft:killed_by.

Should we go along these? or maybe break down further?

2021-07-13 14:56 UTC, RuscalWorld commented
> Sounds good too, do you have any suggestions on how group the different metrices?
Why we need to group metrics? Maybe I misunderstood your question.

But If you want to add ability to disable some metrics, why not do something like this:
```golang
func (e *Exporter) playerStatsCustom(jsonParsed *gabs.Container, desc *prometheus.Desc, field string, ch chan<- prometheus.Metric, playerName string) {
	// Let's imagine that we have "disabledMetrics" - just a map (not array to make search in it easier) that loaded from some file
	// It can be a YAML file, I will leave an example in PR comment
	// I will use map to make searching in it easier
	var disabledMetrics map[string]bool

	// If we have somehing like "stats.minecraft:custom.minecraft:use_cauldron", it will be splitted to
	// "stats", "minecraft:custom" and "minecraft.use_cauldron". Code below checks if some of this values are present
	// in our map and "true" value correspond with some of this values
	// So, if I want to disable all "minecraft:custom", I just add "'minecraft:custom': true" to that YAML file
	// And I can disable certain metric by adding "minecraft.use_cauldron" for example
	for _, group := range strings.Split(field, ".") {
		if value, ok := disabledMetrics[group]; ok && value {
			return
		}
	}

	value, _ := jsonParsed.Path(field).Data().(float64)
	ch <- prometheus.MustNewConstMetric(desc, prometheus.CounterValue, value, playerName)
}
```

And YAML file:
```yaml
disabled-metrics:
  'minecraft:custom': false # will not be disabled
  'minecraft:use_cauldron': true # will be disabled
```

2021-07-13 14:59 UTC, dirien commented
@RuscalWorld ah okay now i got you. So every metric is listed in the yaml an can be individually enabld/disabled.

2021-07-13 17:23 UTC, dirien commented
@RuscalWorld , ca you commit and example config.yaml or extend the README?

2021-07-13 17:26 UTC, dirien commented
And let me know, when you are done, so i can start to review it. 😸 

I have some changes to do to, but i want this PR in  the main branch first 😅

2021-07-13 18:02 UTC, RuscalWorld commented
It looks like that's all I wanted to do

2021-07-14 04:44 UTC, dirien requested changes
LGTM, let one litte comment. After this, i can merge it and release a new version.

FYI: after this i will change some metrics names with the feedback of the official promtheus folks -> https://github.com/prometheus/docs/pull/1988

2021-07-14 04:44 UTC, dirien commented on README.md
> +      --config-path="config.yml"
can you add mc.config-path. so its clear that it belongs to the minecraft part.

2021-07-14 04:44 UTC, dirien commented on pkg/config/config.go
> +		configPath    = kingpin.Flag("config-path", "Path to YAML file with config.").Default("config.yml").String()
can you add mc.config-path. so its clear that it belongs to the minecraft part.

2021-07-14 07:10 UTC, merged

2021-07-14 07:10 UTC, dirien commented
@RuscalWorld , thanks for your great work and input! Much appreciated.